const S={class:"Kelas 1",price:"Rp299K",name:"Rumah Makan NAVA",wa:"628123456789",color:"#111827",sections:[
{type:"hero",title:"Selamat Datang di Rumah Makan NAVA",text:"Masakan lezat, harga bersahabat.",button:"Pesan via WhatsApp"},
{type:"about",title:"Tentang Kami",text:"Cerita bisnis Anda."},
{type:"products",title:"Menu Favorit",items:["Nasi Goreng — Rp20.000","Ayam Geprek — Rp22.000","Es Teh — Rp5.000"]},
{type:"promo",title:"Promo Hari Ini",text:"Diskon spesial untuk pelanggan baru."},
{type:"contact",title:"Hubungi Kami",text:"Alamat • Jam buka • WhatsApp"},
{type:"footer",title:"Terima kasih sudah berkunjung"}]};let selected=-1;
const T={resto:["Rumah Makan NAVA","Selamat Datang di Rumah Makan NAVA",["Nasi Goreng — Rp20.000","Ayam Geprek — Rp22.000","Es Teh — Rp5.000"]],cafe:["NAVA Coffee","Ngopi Santai di NAVA Coffee",["Cappuccino — Rp25.000","Latte — Rp27.000","Croissant — Rp18.000"]],toko:["NAVA Store","Belanja Mudah di NAVA Store",["Produk A — Rp50.000","Produk B — Rp75.000","Produk C — Rp100.000"]],jasa:["NAVA Creative","Solusi Digital untuk Bisnis Anda",["Landing Page — Rp299K","Website Bisnis — Rp499K","Custom Website — Hubungi Kami"]]};
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function body(s){if(s.type==="hero")return `<h1>${esc(s.title)}</h1><p>${esc(s.text)}</p><a class="btn" href="https://wa.me/${S.wa}?text=Halo%20saya%20tertarik" target="_blank">${esc(s.button)}</a>`;if(s.type==="products")return `<h2>${esc(s.title)}</h2><div class="cards">${s.items.map((x,i)=>`<div class="card"><img src="https://picsum.photos/500/300?random=${i+20}"><p><b>${esc(x)}</b></p><a class="btn" href="https://wa.me/${S.wa}?text=${encodeURIComponent("Saya ingin pesan "+x)}" target="_blank">Pesan</a></div>`).join("")}</div>`;return `<h2>${esc(s.title)}</h2><p>${esc(s.text||"")}</p>`}
function render(){document.documentElement.style.setProperty("--accent",S.color);name.value=S.name;wa.value=S.wa;color.value=S.color;title.textContent=S.name;price.textContent=S.class+" • "+S.price;canvas.innerHTML="";S.sections.forEach((s,i)=>{let e=document.createElement("section");e.className=`section ${s.type} ${i===selected?"selected":""}`;e.draggable=true;e.dataset.i=i;e.innerHTML=`<span class="handle">⠿ Drag</span>${body(s)}`;e.onclick=x=>{if(!x.target.closest("a")){selected=i;render()}};e.ondragstart=()=>e.classList.add("dragging");e.ondragend=()=>e.classList.remove("dragging");e.ondragover=x=>x.preventDefault();e.ondrop=x=>{x.preventDefault();let d=document.querySelector(".dragging");if(!d)return;let a=+d.dataset.i,b=i;if(a!==b){let q=S.sections.splice(a,1)[0];S.sections.splice(b,0,q);selected=b;render()}};canvas.appendChild(e)});inspect()}
function inspect(){if(selected<0){edit.textContent="Klik section untuk mengedit.";return}let s=S.sections[selected];edit.innerHTML=`<div class="field"><label>Judul</label><input id="et" value="${esc(s.title)}"></div>${s.text!==undefined?`<div class="field"><label>Isi</label><textarea id="ex" rows="5">${esc(s.text)}</textarea></div>`:""}${s.button!==undefined?`<div class="field"><label>Tombol</label><input id="eb" value="${esc(s.button)}"></div>`:""}${s.items?`<div class="field"><label>Produk/Menu 1 per baris</label><textarea id="ei" rows="6">${s.items.join("\\n")}</textarea></div>`:""}<button id="del">🗑 Hapus Section</button>`;et.oninput=e=>{s.title=e.target.value;render()};if(ex)ex.oninput=e=>{s.text=e.target.value;render()};if(eb)eb.oninput=e=>{s.button=e.target.value;render()};if(ei)ei.oninput=e=>{s.items=e.target.value.split("\\n").filter(Boolean);render()};del.onclick=()=>{S.sections.splice(selected,1);selected=-1;render()}}
document.querySelectorAll(".class").forEach(x=>x.remove());classes.innerHTML=[["Kelas 1","Rp299K"],["Kelas 2","Rp499K"],["Kelas 3","Rp650K"],["Custom","Harga bebas"]].map((x,i)=>`<button class="${i===0?"active":""}" data-i="${i}">${x[0]}<br><b>${x[1]}</b></button>`).join("");document.querySelectorAll("#classes button").forEach(x=>x.onclick=()=>{document.querySelectorAll("#classes button").forEach(y=>y.classList.remove("active"));x.classList.add("active");let i=+x.dataset.i;S.class=i<3?"Kelas "+(i+1):"Custom";S.price=["Rp299K","Rp499K","Rp650K","Harga bebas"][i];render()});
["hero","about","products","promo","contact","footer"].forEach(t=>{let b=document.createElement("button");b.className="add";b.textContent="+ "+t;b.onclick=()=>{let d={hero:{type:t,title:"Judul Hero",text:"Isi hero",button:"Hubungi Kami"},about:{type:t,title:"Tentang Kami",text:"Isi tentang"},products:{type:t,title:"Produk/Menu",items:["Produk 1 — Rp10.000","Produk 2 — Rp20.000"]},promo:{type:t,title:"Promo",text:"Isi promo"},contact:{type:t,title:"Kontak",text:"Alamat • Jam buka"},footer:{type:t,title:"Footer"}};S.sections.push(d);selected=S.sections.length-1;render()};adds.appendChild(b)});
template.onchange=e=>{let t=T[e.target.value];S.name=t[0];S.sections.find(x=>x.type==="hero").title=t[1];S.sections.find(x=>x.type==="products").items=t[2];render()};name.oninput=e=>{S.name=e.target.value;title.textContent=S.name};wa.oninput=e=>S.wa=e.target.value;color.oninput=e=>{S.color=e.target.value;render()};save.onclick=()=>{localStorage.nava=JSON.stringify(S);alert("Project tersimpan.")};load.onclick=()=>{if(localStorage.nava){Object.assign(S,JSON.parse(localStorage.nava));selected=-1;render()}};
function exported(){return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(S.name)}</title><style>body{margin:0;font-family:Arial;color:#172033}section{padding:55px 7%}.hero{background:${S.color};color:white}.btn{display:inline-block;background:${S.color};color:white;padding:10px 15px;border-radius:7px;text-decoration:none}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.card{padding:15px;border:1px solid #ddd;border-radius:10px}.card img{width:100%;height:140px;object-fit:cover}@media(max-width:700px){.cards{grid-template-columns:1fr}}</style></head><body>${S.sections.map(s=>`<section class="${s.type}">${body(s)}</section>`).join("")}</body></html>`}
export.onclick=()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([exported()],{type:"text/html"}));a.download=S.name.replace(/\\s+/g,"-").toLowerCase()+".html";a.click()};preview.onclick=()=>{frame.srcdoc=exported();modal.classList.remove("hide")};close.onclick=()=>modal.classList.add("hide");render();